// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameClassification = "classification"

// Classification mapped from table <classification>
type Classification struct {
	ClassID          int64          `gorm:"column:class_id;primaryKey;autoIncrement:true" json:"class_id"`          // 资源id
	ClassParentID    int64          `gorm:"column:class_parent_id;not null" json:"class_parent_id"`                 // 父分类ID
	ClassName        *string        `gorm:"column:class_name;not null;default:未设置" json:"class_name"`               // 分类名称
	ClassResourceNum *int64         `gorm:"column:class_resource_num" json:"class_resource_num"`                    // 分类下资源数量
	CreateTime       *time.Time     `gorm:"column:create_time;type:int unsigned;autoCreateTime" json:"create_time"` // 创建时间
	UpdateTime       *time.Time     `gorm:"column:update_time;type:int unsigned;autoUpdateTime" json:"update_time"` // 更新时间
	DeleteTime       gorm.DeletedAt `gorm:"column:delete_time" json:"delete_time"`                                  // 删除时间
}

// TableName Classification's table name
func (*Classification) TableName() string {
	return TableNameClassification
}
