// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"gorm.io/gorm"
)

const TableNameMajor = "major"

// Major mapped from table <major>
type Major struct {
	ID         int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // 专业id
	Name       string         `gorm:"column:name;not null" json:"name"`                  // 专业名称
	Desc       *string        `gorm:"column:desc" json:"desc"`                           // 专业描述
	DeleteTime gorm.DeletedAt `gorm:"column:delete_time" json:"delete_time"`             // 删除时间
}

// TableName Major's table name
func (*Major) TableName() string {
	return TableNameMajor
}
