// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	UID        int64          `gorm:"column:uid;primaryKey;autoIncrement:true" json:"uid"`                    // 数据表自增ID
	UniqueID   int64          `gorm:"column:unique_id;not null" json:"unique_id"`                             // 用户唯一数据id
	Name       string         `gorm:"column:name;not null" json:"name"`                                       // 用户名称
	Password   string         `gorm:"column:password;not null" json:"password"`                               // 用户密码
	Age        *int64         `gorm:"column:age" json:"age"`                                                  // 用户年龄
	Gender     *int64         `gorm:"column:gender" json:"gender"`                                            // 用户性别 1男2女3未设置
	Phone      string         `gorm:"column:phone;not null" json:"phone"`                                     // 用户电话
	Email      *string        `gorm:"column:email" json:"email"`                                              // 用户邮箱
	Grade      *int64         `gorm:"column:grade" json:"grade"`                                              // 用户年纪 （大一、大二、大三、大四） 1，2，3，4
	Major      *int64         `gorm:"column:major" json:"major"`                                              // 用户专业信息(关联字段)
	Star       *float32       `gorm:"column:star" json:"star"`                                                // 用户等级(0~5)
	Avatar     *string        `gorm:"column:avatar" json:"avatar"`                                            // 用户头像链接
	Sign       *string        `gorm:"column:sign" json:"sign"`                                                // 用户个性签名
	Class      *int64         `gorm:"column:class" json:"class"`                                              // 用户班级
	CreateTime *time.Time     `gorm:"column:create_time;type:int unsigned;autoCreateTime" json:"create_time"` // 创建时间
	UpdateTime *time.Time     `gorm:"column:update_time;type:int unsigned;autoUpdateTime" json:"update_time"` // 更新时间
	DeleteTime gorm.DeletedAt `gorm:"column:delete_time" json:"delete_time"`                                  // 删除时间
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
