// Code generated by goctl. DO NOT EDIT.
package types

type UserLoginReq struct {
	UserName string `json:"userName"`
	Passwd   string `json:"passwd"`
}

type UserLoginResp struct {
	Token string `json:"token"`
}
