// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameOrder = "order"

// Order mapped from table <order>
type Order struct {
	ID              int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                      // 订单id
	UUID            int64          `gorm:"column:uuid;not null" json:"uuid"`                                       // 唯一订单流水号
	ProductID       int64          `gorm:"column:product_id;not null" json:"product_id"`                           // 商品中的商品id
	SysModel        int64          `gorm:"column:sys_model;not null" json:"sys_model"`                             // 订单来源模块（0 商品模块）
	Status          int64          `gorm:"column:status;not null" json:"status"`                                   // 订单状态（0:创建    1:付款中   2:付款成功    3:已发货   4:用户已确认）
	UserID          int64          `gorm:"column:user_id;not null" json:"user_id"`                                 // 下订单用户id
	PayPrice        *float64       `gorm:"column:pay_price;not null;default:0.0000" json:"pay_price"`              // 实际订单生成金额
	PayPath         int64          `gorm:"column:pay_path;not null" json:"pay_path"`                               // 支付渠道（0:微信  1:支付宝 ）
	PayPathOrderNum string         `gorm:"column:pay_path_order_num;not null" json:"pay_path_order_num"`           // 支付渠道流水号
	PayCodeURL      *string        `gorm:"column:pay_code_url" json:"pay_code_url"`                                // 支付渠道二维码链接
	CreateTime      *time.Time     `gorm:"column:create_time;type:int unsigned;autoCreateTime" json:"create_time"` // 创建时间
	UpdateTime      *time.Time     `gorm:"column:update_time;type:int unsigned;autoUpdateTime" json:"update_time"` // update_time
	DeleteTime      gorm.DeletedAt `gorm:"column:delete_time" json:"delete_time"`                                  // 删除时间
}

// TableName Order's table name
func (*Order) TableName() string {
	return TableNameOrder
}
