// Code generated by goctl. DO NOT EDIT.
// Source: resourcesrpc.proto

package resourcesrpc

import (
	"context"

	"github.com/baiyz0825/school-share-buy-backend/apps/resources/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddClassificationReq              = pb.AddClassificationReq
	AddClassificationResp             = pb.AddClassificationResp
	AddCountReq                       = pb.AddCountReq
	AddCountResp                      = pb.AddCountResp
	AddFileReq                        = pb.AddFileReq
	AddFileResp                       = pb.AddFileResp
	AddOnlineTextReq                  = pb.AddOnlineTextReq
	AddOnlineTextResp                 = pb.AddOnlineTextResp
	AddResCommentReq                  = pb.AddResCommentReq
	AddResCommentResp                 = pb.AddResCommentResp
	CheckDownloadAllowReq             = pb.CheckDownloadAllowReq
	CheckDownloadAllowResp            = pb.CheckDownloadAllowResp
	Classification                    = pb.Classification
	ClassificationDataByPagesReq      = pb.ClassificationDataByPagesReq
	ClassificationDataByPagesResp     = pb.ClassificationDataByPagesResp
	ClassificationTreeMenu            = pb.ClassificationTreeMenu
	Count                             = pb.Count
	DelClassificationReq              = pb.DelClassificationReq
	DelClassificationResp             = pb.DelClassificationResp
	DelCountReq                       = pb.DelCountReq
	DelCountResp                      = pb.DelCountResp
	DelFileReq                        = pb.DelFileReq
	DelFileResp                       = pb.DelFileResp
	DelOnlineTextReq                  = pb.DelOnlineTextReq
	DelOnlineTextResp                 = pb.DelOnlineTextResp
	DelResCommentReq                  = pb.DelResCommentReq
	DelResCommentResp                 = pb.DelResCommentResp
	File                              = pb.File
	GetClassificationByIdReq          = pb.GetClassificationByIdReq
	GetClassificationByIdResp         = pb.GetClassificationByIdResp
	GetCountByIdReq                   = pb.GetCountByIdReq
	GetCountByIdResp                  = pb.GetCountByIdResp
	GetCountByUIdReq                  = pb.GetCountByUIdReq
	GetCountByUIdResp                 = pb.GetCountByUIdResp
	GetFilResourcesUSerIdReq          = pb.GetFilResourcesUSerIdReq
	GetFilResourcesUSerIdResp         = pb.GetFilResourcesUSerIdResp
	GetFileByIdReq                    = pb.GetFileByIdReq
	GetFileByIdResp                   = pb.GetFileByIdResp
	GetOnlineTextByIdReq              = pb.GetOnlineTextByIdReq
	GetOnlineTextByIdResp             = pb.GetOnlineTextByIdResp
	GetResCommentByIdReq              = pb.GetResCommentByIdReq
	GetResCommentByIdResp             = pb.GetResCommentByIdResp
	OnlineText                        = pb.OnlineText
	ResComment                        = pb.ResComment
	SearchClassificationAllReq        = pb.SearchClassificationAllReq
	SearchClassificationAllResp       = pb.SearchClassificationAllResp
	SearchFileConditionReq            = pb.SearchFileConditionReq
	SearchFileConditionResp           = pb.SearchFileConditionResp
	SearchOnlineConditionTextReq      = pb.SearchOnlineConditionTextReq
	SearchOnlineTextConditionResp     = pb.SearchOnlineTextConditionResp
	SearchResCommentByUserOrResIdReq  = pb.SearchResCommentByUserOrResIdReq
	SearchResCommentByUserOrResIdResp = pb.SearchResCommentByUserOrResIdResp
	UpdateClassificationReq           = pb.UpdateClassificationReq
	UpdateClassificationResp          = pb.UpdateClassificationResp
	UpdateCountReq                    = pb.UpdateCountReq
	UpdateCountResp                   = pb.UpdateCountResp
	UpdateFileReq                     = pb.UpdateFileReq
	UpdateFileResp                    = pb.UpdateFileResp
	UpdateOnlineTextReq               = pb.UpdateOnlineTextReq
	UpdateOnlineTextResp              = pb.UpdateOnlineTextResp
	UpdateResCommentReq               = pb.UpdateResCommentReq
	UpdateResCommentResp              = pb.UpdateResCommentResp

	Resourcesrpc interface {
		// -----------------------资源分类信息-----------------------
		AddClassification(ctx context.Context, in *AddClassificationReq, opts ...grpc.CallOption) (*AddClassificationResp, error)
		UpdateClassification(ctx context.Context, in *UpdateClassificationReq, opts ...grpc.CallOption) (*UpdateClassificationResp, error)
		DelClassification(ctx context.Context, in *DelClassificationReq, opts ...grpc.CallOption) (*DelClassificationResp, error)
		GetClassificationById(ctx context.Context, in *GetClassificationByIdReq, opts ...grpc.CallOption) (*GetClassificationByIdResp, error)
		// 查询全部分类
		SearchClassificationAll(ctx context.Context, in *SearchClassificationAllReq, opts ...grpc.CallOption) (*SearchClassificationAllResp, error)
		// 分类查询分类id下的资源
		GetClassificationDataByPages(ctx context.Context, in *ClassificationDataByPagesReq, opts ...grpc.CallOption) (*ClassificationDataByPagesResp, error)
		// -----------------------用户上传资源量统计信息-----------------------
		AddCount(ctx context.Context, in *AddCountReq, opts ...grpc.CallOption) (*AddCountResp, error)
		UpdateCount(ctx context.Context, in *UpdateCountReq, opts ...grpc.CallOption) (*UpdateCountResp, error)
		DelCount(ctx context.Context, in *DelCountReq, opts ...grpc.CallOption) (*DelCountResp, error)
		GetCountById(ctx context.Context, in *GetCountByIdReq, opts ...grpc.CallOption) (*GetCountByIdResp, error)
		GetCountByUId(ctx context.Context, in *GetCountByUIdReq, opts ...grpc.CallOption) (*GetCountByUIdResp, error)
		// -----------------------文件资源存储表（非文本类型）-----------------------
		AddFile(ctx context.Context, in *AddFileReq, opts ...grpc.CallOption) (*AddFileResp, error)
		UpdateFile(ctx context.Context, in *UpdateFileReq, opts ...grpc.CallOption) (*UpdateFileResp, error)
		DelFile(ctx context.Context, in *DelFileReq, opts ...grpc.CallOption) (*DelFileResp, error)
		GetFileById(ctx context.Context, in *GetFileByIdReq, opts ...grpc.CallOption) (*GetFileByIdResp, error)
		// 多条件查询（大类，用户id / 全部文件中筛选）
		SearchFileConditionPages(ctx context.Context, in *SearchFileConditionReq, opts ...grpc.CallOption) (*SearchFileConditionResp, error)
		// 检查文件是否允许下载
		CheckDownloadAllow(ctx context.Context, in *CheckDownloadAllowReq, opts ...grpc.CallOption) (*CheckDownloadAllowResp, error)
		GetFilResourcesUSerId(ctx context.Context, in *GetFilResourcesUSerIdReq, opts ...grpc.CallOption) (*GetFilResourcesUSerIdResp, error)
		// -----------------------在线文本资源信息-----------------------
		AddOnlineText(ctx context.Context, in *AddOnlineTextReq, opts ...grpc.CallOption) (*AddOnlineTextResp, error)
		UpdateOnlineText(ctx context.Context, in *UpdateOnlineTextReq, opts ...grpc.CallOption) (*UpdateOnlineTextResp, error)
		DelOnlineText(ctx context.Context, in *DelOnlineTextReq, opts ...grpc.CallOption) (*DelOnlineTextResp, error)
		GetOnlineTextById(ctx context.Context, in *GetOnlineTextByIdReq, opts ...grpc.CallOption) (*GetOnlineTextByIdResp, error)
		// 多条件查询（大类，用户id / 全部文件中筛选）
		SearchOnlineConditionText(ctx context.Context, in *SearchOnlineConditionTextReq, opts ...grpc.CallOption) (*SearchOnlineTextConditionResp, error)
		// -----------------------资源评论信息-----------------------
		AddResComment(ctx context.Context, in *AddResCommentReq, opts ...grpc.CallOption) (*AddResCommentResp, error)
		UpdateResComment(ctx context.Context, in *UpdateResCommentReq, opts ...grpc.CallOption) (*UpdateResCommentResp, error)
		DelResComment(ctx context.Context, in *DelResCommentReq, opts ...grpc.CallOption) (*DelResCommentResp, error)
		GetResCommentById(ctx context.Context, in *GetResCommentByIdReq, opts ...grpc.CallOption) (*GetResCommentByIdResp, error)
		// 查询某一个资源下评论 ， 查询用户全部评论
		SearchResCommentByUserOrResId(ctx context.Context, in *SearchResCommentByUserOrResIdReq, opts ...grpc.CallOption) (*SearchResCommentByUserOrResIdResp, error)
	}

	defaultResourcesrpc struct {
		cli zrpc.Client
	}
)

func NewResourcesrpc(cli zrpc.Client) Resourcesrpc {
	return &defaultResourcesrpc{
		cli: cli,
	}
}

// -----------------------资源分类信息-----------------------
func (m *defaultResourcesrpc) AddClassification(ctx context.Context, in *AddClassificationReq, opts ...grpc.CallOption) (*AddClassificationResp, error) {
	client := pb.NewResourcesrpcClient(m.cli.Conn())
	return client.AddClassification(ctx, in, opts...)
}

func (m *defaultResourcesrpc) UpdateClassification(ctx context.Context, in *UpdateClassificationReq, opts ...grpc.CallOption) (*UpdateClassificationResp, error) {
	client := pb.NewResourcesrpcClient(m.cli.Conn())
	return client.UpdateClassification(ctx, in, opts...)
}

func (m *defaultResourcesrpc) DelClassification(ctx context.Context, in *DelClassificationReq, opts ...grpc.CallOption) (*DelClassificationResp, error) {
	client := pb.NewResourcesrpcClient(m.cli.Conn())
	return client.DelClassification(ctx, in, opts...)
}

func (m *defaultResourcesrpc) GetClassificationById(ctx context.Context, in *GetClassificationByIdReq, opts ...grpc.CallOption) (*GetClassificationByIdResp, error) {
	client := pb.NewResourcesrpcClient(m.cli.Conn())
	return client.GetClassificationById(ctx, in, opts...)
}

// 查询全部分类
func (m *defaultResourcesrpc) SearchClassificationAll(ctx context.Context, in *SearchClassificationAllReq, opts ...grpc.CallOption) (*SearchClassificationAllResp, error) {
	client := pb.NewResourcesrpcClient(m.cli.Conn())
	return client.SearchClassificationAll(ctx, in, opts...)
}

// 分类查询分类id下的资源
func (m *defaultResourcesrpc) GetClassificationDataByPages(ctx context.Context, in *ClassificationDataByPagesReq, opts ...grpc.CallOption) (*ClassificationDataByPagesResp, error) {
	client := pb.NewResourcesrpcClient(m.cli.Conn())
	return client.GetClassificationDataByPages(ctx, in, opts...)
}

// -----------------------用户上传资源量统计信息-----------------------
func (m *defaultResourcesrpc) AddCount(ctx context.Context, in *AddCountReq, opts ...grpc.CallOption) (*AddCountResp, error) {
	client := pb.NewResourcesrpcClient(m.cli.Conn())
	return client.AddCount(ctx, in, opts...)
}

func (m *defaultResourcesrpc) UpdateCount(ctx context.Context, in *UpdateCountReq, opts ...grpc.CallOption) (*UpdateCountResp, error) {
	client := pb.NewResourcesrpcClient(m.cli.Conn())
	return client.UpdateCount(ctx, in, opts...)
}

func (m *defaultResourcesrpc) DelCount(ctx context.Context, in *DelCountReq, opts ...grpc.CallOption) (*DelCountResp, error) {
	client := pb.NewResourcesrpcClient(m.cli.Conn())
	return client.DelCount(ctx, in, opts...)
}

func (m *defaultResourcesrpc) GetCountById(ctx context.Context, in *GetCountByIdReq, opts ...grpc.CallOption) (*GetCountByIdResp, error) {
	client := pb.NewResourcesrpcClient(m.cli.Conn())
	return client.GetCountById(ctx, in, opts...)
}

func (m *defaultResourcesrpc) GetCountByUId(ctx context.Context, in *GetCountByUIdReq, opts ...grpc.CallOption) (*GetCountByUIdResp, error) {
	client := pb.NewResourcesrpcClient(m.cli.Conn())
	return client.GetCountByUId(ctx, in, opts...)
}

// -----------------------文件资源存储表（非文本类型）-----------------------
func (m *defaultResourcesrpc) AddFile(ctx context.Context, in *AddFileReq, opts ...grpc.CallOption) (*AddFileResp, error) {
	client := pb.NewResourcesrpcClient(m.cli.Conn())
	return client.AddFile(ctx, in, opts...)
}

func (m *defaultResourcesrpc) UpdateFile(ctx context.Context, in *UpdateFileReq, opts ...grpc.CallOption) (*UpdateFileResp, error) {
	client := pb.NewResourcesrpcClient(m.cli.Conn())
	return client.UpdateFile(ctx, in, opts...)
}

func (m *defaultResourcesrpc) DelFile(ctx context.Context, in *DelFileReq, opts ...grpc.CallOption) (*DelFileResp, error) {
	client := pb.NewResourcesrpcClient(m.cli.Conn())
	return client.DelFile(ctx, in, opts...)
}

func (m *defaultResourcesrpc) GetFileById(ctx context.Context, in *GetFileByIdReq, opts ...grpc.CallOption) (*GetFileByIdResp, error) {
	client := pb.NewResourcesrpcClient(m.cli.Conn())
	return client.GetFileById(ctx, in, opts...)
}

// 多条件查询（大类，用户id / 全部文件中筛选）
func (m *defaultResourcesrpc) SearchFileConditionPages(ctx context.Context, in *SearchFileConditionReq, opts ...grpc.CallOption) (*SearchFileConditionResp, error) {
	client := pb.NewResourcesrpcClient(m.cli.Conn())
	return client.SearchFileConditionPages(ctx, in, opts...)
}

// 检查文件是否允许下载
func (m *defaultResourcesrpc) CheckDownloadAllow(ctx context.Context, in *CheckDownloadAllowReq, opts ...grpc.CallOption) (*CheckDownloadAllowResp, error) {
	client := pb.NewResourcesrpcClient(m.cli.Conn())
	return client.CheckDownloadAllow(ctx, in, opts...)
}

func (m *defaultResourcesrpc) GetFilResourcesUSerId(ctx context.Context, in *GetFilResourcesUSerIdReq, opts ...grpc.CallOption) (*GetFilResourcesUSerIdResp, error) {
	client := pb.NewResourcesrpcClient(m.cli.Conn())
	return client.GetFilResourcesUSerId(ctx, in, opts...)
}

// -----------------------在线文本资源信息-----------------------
func (m *defaultResourcesrpc) AddOnlineText(ctx context.Context, in *AddOnlineTextReq, opts ...grpc.CallOption) (*AddOnlineTextResp, error) {
	client := pb.NewResourcesrpcClient(m.cli.Conn())
	return client.AddOnlineText(ctx, in, opts...)
}

func (m *defaultResourcesrpc) UpdateOnlineText(ctx context.Context, in *UpdateOnlineTextReq, opts ...grpc.CallOption) (*UpdateOnlineTextResp, error) {
	client := pb.NewResourcesrpcClient(m.cli.Conn())
	return client.UpdateOnlineText(ctx, in, opts...)
}

func (m *defaultResourcesrpc) DelOnlineText(ctx context.Context, in *DelOnlineTextReq, opts ...grpc.CallOption) (*DelOnlineTextResp, error) {
	client := pb.NewResourcesrpcClient(m.cli.Conn())
	return client.DelOnlineText(ctx, in, opts...)
}

func (m *defaultResourcesrpc) GetOnlineTextById(ctx context.Context, in *GetOnlineTextByIdReq, opts ...grpc.CallOption) (*GetOnlineTextByIdResp, error) {
	client := pb.NewResourcesrpcClient(m.cli.Conn())
	return client.GetOnlineTextById(ctx, in, opts...)
}

// 多条件查询（大类，用户id / 全部文件中筛选）
func (m *defaultResourcesrpc) SearchOnlineConditionText(ctx context.Context, in *SearchOnlineConditionTextReq, opts ...grpc.CallOption) (*SearchOnlineTextConditionResp, error) {
	client := pb.NewResourcesrpcClient(m.cli.Conn())
	return client.SearchOnlineConditionText(ctx, in, opts...)
}

// -----------------------资源评论信息-----------------------
func (m *defaultResourcesrpc) AddResComment(ctx context.Context, in *AddResCommentReq, opts ...grpc.CallOption) (*AddResCommentResp, error) {
	client := pb.NewResourcesrpcClient(m.cli.Conn())
	return client.AddResComment(ctx, in, opts...)
}

func (m *defaultResourcesrpc) UpdateResComment(ctx context.Context, in *UpdateResCommentReq, opts ...grpc.CallOption) (*UpdateResCommentResp, error) {
	client := pb.NewResourcesrpcClient(m.cli.Conn())
	return client.UpdateResComment(ctx, in, opts...)
}

func (m *defaultResourcesrpc) DelResComment(ctx context.Context, in *DelResCommentReq, opts ...grpc.CallOption) (*DelResCommentResp, error) {
	client := pb.NewResourcesrpcClient(m.cli.Conn())
	return client.DelResComment(ctx, in, opts...)
}

func (m *defaultResourcesrpc) GetResCommentById(ctx context.Context, in *GetResCommentByIdReq, opts ...grpc.CallOption) (*GetResCommentByIdResp, error) {
	client := pb.NewResourcesrpcClient(m.cli.Conn())
	return client.GetResCommentById(ctx, in, opts...)
}

// 查询某一个资源下评论 ， 查询用户全部评论
func (m *defaultResourcesrpc) SearchResCommentByUserOrResId(ctx context.Context, in *SearchResCommentByUserOrResIdReq, opts ...grpc.CallOption) (*SearchResCommentByUserOrResIdResp, error) {
	client := pb.NewResourcesrpcClient(m.cli.Conn())
	return client.SearchResCommentByUserOrResId(ctx, in, opts...)
}
