// Code generated by goctl. DO NOT EDIT.
package types

type SocialBind struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

type User struct {
	UserId       int64        `json:"userId"`
	UserUniqueId int64        `json:"userUniqueId"`
	UserName     string       `json:"userName"`
	Age          int64        `json:"age"`
	Gender       string       `json:"gender"`
	Phone        string       `json:"phone"`
	Email        string       `json:"email"`
	Grade        string       `json:"grade"`
	Major        string       `json:"major"`
	Star         string       `json:"star"`
	Avatar       string       `json:"avatar"`
	Sign         string       `json:"sign"`
	Class        string       `json:"class"`
	SocialBind   []SocialBind `json:"socialBind"`
}

type LoginReq struct {
	Phone     string `form:"phone" validate:"required,zh_cn_phone"`
	Email     string `form:"email,optional" validate:"omitempty,email"`
	Password  string `form:"password" validate:"required,password"`
	Captcha   string `form:"captcha" validate:"required"`
	CaptchaId string `form:"captchaId" validate:"required"`
}

type LoginResp struct {
	AccessToken string `json:"accessToken"`
	ExpireTime  string `json:"expireTime"`
}

type ChaptchaResp struct {
	CaptchaB64 string `json:"captchaB64"`
	CaptchaId  string `json:"captchaId"`
}

type RegisterReq struct {
	Username  string `form:"username" validate:"required"`
	Password  string `form:"password" validate:"required,password"`
	Phone     string `form:"phone" validate:"required,zh_cn_phone"`
	Captcha   string `form:"captcha" validate:"required"`
	CaptchaId string `form:"captchaId" validate:"required"`
}

type RegisterResp struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	ExpireTime   string `json:"expireTime"`
}

type UserInfoResp struct {
	UserInfo User `json:"userInfo"`
}

type UserDataReq struct {
	Username  string `form:"username" validate:"required"`
	Passsword string `form:"passsword" validate:"required,password"`
	Sign      string `form:"sign,optional"`
	Phone     string `form:"phone" validate:"required,zh_cn_phone"`
	Email     string `form:"email" validate:"required,email"`
	Age       int64  `form:"age,optional" validate:"omitempty,gte=0,lte=120"`
	Gender    int64  `form:"gender,optional"`
	Major     int64  `form:"major,optional"`
	Grade     int64  `form:"grade,optional"`
	Class     int64  `form:"class,optional"`
}

type Major struct {
	ID   int64  `json:"id"`   //专业ID
	Name string `json:"name"` //专业名称
	Desc string `json:"desc"` //专业描述
}

type GetAllMajorsResp struct {
	Major []Major `json:"major"`
}
